name: Deploy App to Cloudflare Pages
on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'package.json'
      - '.github/workflows/deploy-app-main.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build App
        working-directory: apps/web
        run: |
          yarn build

      - name: Deploy App to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/web
          command: pages deploy out --project-name=app-sol-learn
